# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Katana.create(id: 1, name: '岩融', furigana: 'いわとおし', katana_type: 7, tantou_time: 300, forgeable: true, rare: true)
Katana.create(id: 2, name: '巴形薙刀', furigana: 'ともえがたなぎなた', katana_type: 7, tantou_time: 300, forgeable: true, rare: true)
Katana.create(id: 3, name: '静形薙刀', furigana: 'しずかがたなぎなた', katana_type: 7, tantou_time: 300, forgeable: true, rare: true)
Katana.create(id: 4, name: 'にっかり青江', furigana: 'にっかりあおえ', katana_type: 2, tantou_time: 40, forgeable: true, rare: false)
Katana.create(id: 5, name: '鯰尾藤四郎', furigana: 'なまずおとうしろう', katana_type: 2, tantou_time: 40, forgeable: true, rare: false)
Katana.create(id: 6, name: '骨喰藤四郎', furigana: 'ほねばみとうしろう', katana_type: 2, tantou_time: 40, forgeable: true, rare: false)
Katana.create(id: 7, name: '物吉貞宗', furigana: 'ものよしさだむね', katana_type: 2, tantou_time: 40, forgeable: true, rare: true)
Katana.create(id: 8, name: '堀川国広', furigana: 'ほりかわくにひろ', katana_type: 2, tantou_time: 40, forgeable: true, rare: false)
Katana.create(id: 9, name: '浦島虎徹', furigana: 'うらしまこてつ', katana_type: 2, tantou_time: 40, forgeable: true, rare: true)
Katana.create(id: 10, name: '篭手切江', furigana: 'こてぎりごう', katana_type: 2, tantou_time: 40, forgeable: false, rare: true)
Katana.create(id: 11, name: '今剣', furigana: 'いまのつるぎ', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 12, name: '平野藤四郎', furigana: 'ひらのとうしろう', katana_type: 1, tantou_time: 30, forgeable: true, rare: true)
Katana.create(id: 13, name: '厚藤四郎', furigana: 'あつしとうしろう', katana_type: 1, tantou_time: 30, forgeable: true, rare: true)
Katana.create(id: 14, name: '後藤藤四郎', furigana: 'ごとうとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 15, name: '信濃藤四郎', furigana: 'しなのとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 16, name: '前田藤四郎', furigana: 'まえだとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 17, name: '秋田藤四郎', furigana: 'あきたとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 18, name: '博多藤四郎', furigana: 'はかたとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 19, name: '乱藤四郎', furigana: 'みだれとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 20, name: '五虎退', furigana: 'ごこたい', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 21, name: '薬研藤四郎', furigana: 'やげんとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 22, name: '包丁藤四郎', furigana: 'ほうちょうとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 23, name: '愛染国俊', furigana: 'あいぜんくにとし', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 24, name: '太鼓鐘貞宗', furigana: 'たいこがねさだむね,さだちゃん', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 25, name: '小夜左文字', furigana: 'さよさもんじ,おさよ', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 26, name: '不動行光', furigana: 'ふどうゆきみつ', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 27, name: '毛利藤四郎', furigana: 'もうりとうしろう', katana_type: 1, tantou_time: 20, forgeable: true, rare: false)
Katana.create(id: 28, name: '謙信景光', furigana: 'けんしんかげみつ', katana_type: 1, tantou_time: 30, forgeable: true, rare: true)
Katana.create(id: 29, name: '日向正宗', furigana: 'ひゅうがまさむね', katana_type: 1, tantou_time: 30, forgeable: false, rare: true)
Katana.create(id: 30, name: '蜻蛉切', furigana: 'とんぼぎり', katana_type: 6, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 31, name: '日本号', furigana: 'にほんごう', katana_type: 6, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 32, name: '御手杵', furigana: 'おてぎね', katana_type: 6, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 33, name: '鳴狐', furigana: 'なきぎつね', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 34, name: '千子村正', furigana: 'せんごむらまさ', katana_type: 3, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 35, name: '亀甲貞宗', furigana: 'きっこうさだむね', katana_type: 3, tantou_time: 90, forgeable: true, rare: true)
Katana.create(id: 36, name: '宗三左文字', furigana: 'そうざさもんじ', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 37, name: '加州清光', furigana: 'かしゅうきよみつ', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 38, name: '大和守安定', furigana: 'やまとのかみやすさだ', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 39, name: '歌仙兼定', furigana: 'かせんかねさだ', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 40, name: '和泉守兼定', furigana: 'いずみのかみかねさだ', katana_type: 3, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 41, name: '陸奥守吉行', furigana: 'むつのかみよしゆき', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 42, name: '山姥切国広', furigana: 'やまんばぎりくにひろ', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 43, name: '蜂須賀虎徹', furigana: 'はちすかこてつ,はっち', katana_type: 3, tantou_time: 90, forgeable: true, rare: false)
Katana.create(id: 44, name: '長曽祢虎徹', furigana: 'ながそねこてつ', katana_type: 3, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 45, name: '大倶利伽羅', furigana: 'おおくりから', katana_type: 3, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 46, name: 'へし切長谷部', furigana: 'へしきりはせべ', katana_type: 3, tantou_time: 150, forgeable: true, rare: false)
Katana.create(id: 47, name: '同田貫正国', furigana: 'どうだぬきまさくに,たぬき', katana_type: 3, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 48, name: '南泉一文字', furigana: 'なんせんいちもんじ,にゃん', katana_type: 3, tantou_time: 90, forgeable: false, rare: true)
Katana.create(id: 49, name: '山姥切長義', furigana: 'やまんばぎりちょうぎ,ちょぎ', katana_type: 3, tantou_time: 90, forgeable: false, rare: true)
Katana.create(id: 50, name: '豊前江', furigana: 'ぶぜんごう', katana_type: 3, tantou_time: 90, forgeable: false, rare: true)
Katana.create(id: 51, name: '三日月宗近', furigana: 'みかづきむねちか,おじい,じじ', katana_type: 4, tantou_time: 240, forgeable: true, rare: true)
Katana.create(id: 52, name: '小狐丸', furigana: 'こぎつねまる', katana_type: 4, tantou_time: 240, forgeable: true, rare: true)
Katana.create(id: 53, name: '大典太光世', furigana: 'おおでんたみつよ', katana_type: 4, tantou_time: 240, forgeable: false, rare: true)
Katana.create(id: 54, name: 'ソハヤノツルキ', furigana: 'そはやのつるぎ', katana_type: 4, tantou_time: 240, forgeable: false, rare: true)
Katana.create(id: 55, name: '数珠丸恒次', furigana: 'じゅずまるかねつぐ,ずず', katana_type: 4, tantou_time: 240, forgeable: true, rare: true)
Katana.create(id: 56, name: '一期一振', furigana: 'いちごひとふり', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 57, name: '大包平', furigana: 'おおかねひら', katana_type: 4, tantou_time: 240, forgeable: false, rare: true)
Katana.create(id: 58, name: '鶯丸', furigana: 'うぐいすまる', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 59, name: '明石国行', furigana: 'あかしくにゆき', katana_type: 4, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 60, name: '燭台切光忠', furigana: 'しょくだいきりみつただ,みっちゃん', katana_type: 4, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 61, name: '大般若長光', furigana: 'だいはんにゃながみつ', katana_type: 4, tantou_time: 200, forgeable: false, rare: true)
Katana.create(id: 62, name: '小竜景光', furigana: 'こりゅうかげみつ', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 63, name: '江雪左文字', furigana: 'こうせつさもんじ', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 64, name: '山伏国広', furigana: 'やまぶしくにひろ', katana_type: 4, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 65, name: '髭切', furigana: 'ひげきり,あにじゃ,兄', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 66, name: '膝丸', furigana: 'ひざまる', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 67, name: '獅子王', furigana: 'ししおう', katana_type: 4, tantou_time: 180, forgeable: true, rare: false)
Katana.create(id: 68, name: '小烏丸', furigana: 'こがらすまる,父,ぱぱ', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 69, name: '鶴丸国永', furigana: 'つるまるくになが', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 70, name: '小豆長光', furigana: 'あずきながみつ', katana_type: 4, tantou_time: 200, forgeable: true, rare: true)
Katana.create(id: 71, name: '千代金丸', furigana: 'ちよがねまる', katana_type: 4, tantou_time: 200, forgeable: false, rare: true)
Katana.create(id: 72, name: '石切丸', furigana: 'いしきりまる,ぱぱ', katana_type: 5, tantou_time: 150, forgeable: true, rare: false)
Katana.create(id: 73, name: '蛍丸', furigana: 'ほたるまる', katana_type: 5, tantou_time: 180, forgeable: true, rare: true)
Katana.create(id: 74, name: '太郎太刀', furigana: 'たろうたち', katana_type: 5, tantou_time: 150, forgeable: true, rare: false)
Katana.create(id: 75, name: '次郎太刀', furigana: 'じろうたち', katana_type: 5, tantou_time: 150, forgeable: true, rare: false)
Katana.create(id: 76, name: '祢々切丸', furigana: 'ねねきりまる', katana_type: 5, tantou_time: 150, forgeable: false, rare: true)
Katana.create(id: 77, name: '白山吉光', furigana: 'はくさんよしみつ', katana_type: 8, tantou_time: 360, forgeable: false, rare: true)